# Generated by Django 5.0.7 on 2024-07-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='password',
            field=models.CharField(default='0000', max_length=30),
        ),
    ]
