# Generated by Django 5.0.7 on 2024-07-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equal', '0002_player_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
