# Generated by Django 5.0.7 on 2024-07-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equal', '0005_remove_player_date_joined_remove_player_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='highscore',
            field=models.IntegerField(default=0),
        ),
    ]
