# Generated by Django 5.0.7 on 2024-07-14 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equal', '0006_alter_player_gold_alter_player_highscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
